In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [8]:
a=np.array([1,2,3,4],dtype=float)
print(a)

[1. 2. 3. 4.]


In [14]:
a=np.array([1,2,3,4],dtype=str)
print(a)

['1' '2' '3' '4']


In [9]:
len(a)

4

In [10]:
b=np.array([[1,2,3,4,5],[5,4,33,2,2]])
print(b)

[[ 1  2  3  4  5]
 [ 5  4 33  2  2]]


In [11]:
len(b)

2

In [13]:
b.ndim #dimensions

2

In [18]:
#shape of np array
a=np.array([[1,2,3,4]])
a.shape

(1, 4)

In [21]:
b=np.array([[1,2,3,4,5],[5,4,33,2,5]])
b.shape

(2, 5)

In [24]:
b=np.array([[1,2,3,4,5],[5,4,33,2,2],[1,2,3,4,5]])
b.shape

(3, 5)

In [26]:
b.dtype

dtype('int64')

In [27]:
a

array([[1, 2, 3, 4]])

In [31]:
print(a[0][0])

25


In [30]:
a[0][0]=25
print(a)

[[25  2  3  4]]


In [32]:
print(b)

[[ 1  2  3  4  5]
 [ 5  4 33  2  2]
 [ 1  2  3  4  5]]


In [33]:
b[1][2]=9

In [34]:
print(b)

[[1 2 3 4 5]
 [5 4 9 2 2]
 [1 2 3 4 5]]


In [37]:
#zeros and ones method
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
print(np.full((3,3),17,dtype='int'))

[[17 17 17]
 [17 17 17]
 [17 17 17]]


In [51]:
np.random.rand(4,4)

array([[0.030002  , 0.83348562, 0.25630965, 0.39496256],
       [0.34909169, 0.72791119, 0.92784058, 0.55889739],
       [0.46722201, 0.0493593 , 0.83378604, 0.06984029],
       [0.79054902, 0.86968333, 0.82389344, 0.637758  ]])

In [53]:
np.random.randint(1,31,size=(4,4))

array([[22, 14, 30, 26],
       [ 2, 18, 30, 23],
       [11, 23,  8, 14],
       [21, 18, 11,  1]], dtype=int32)

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Q. Extract first 3 rows from last 5 columns in given np 2D array

a=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[11,21,31,41,51,61],[15,25,35,45,55,65]]


In [55]:
a=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[11,21,31,41,51,61],[15,25,35,45,55,65]])
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [11 21 31 41 51 61]
 [15 25 35 45 55 65]]


In [57]:
print(a[0:3,-5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [21 31 41 51 61]]


In [82]:
n=3
z=np.zeros((n,n),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
mid=n//2
z[mid,:]=1
z[:,mid]=1
print(z)

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [84]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [11, 21, 31, 41, 51, 61],
       [15, 25, 35, 45, 55, 65]])

In [85]:
b

array([[1, 2, 3, 4, 5],
       [5, 4, 9, 2, 2],
       [1, 2, 3, 4, 5]])

In [86]:
a.mean()

np.float64(28.625)

In [87]:
a.max()

np.int64(65)

In [88]:
a.min()

np.int64(1)

In [89]:
a+5

array([[ 6,  7,  8,  9, 10, 11],
       [15, 25, 35, 45, 55, 65],
       [16, 26, 36, 46, 56, 66],
       [20, 30, 40, 50, 60, 70]])

In [90]:
a*2

array([[  2,   4,   6,   8,  10,  12],
       [ 20,  40,  60,  80, 100, 120],
       [ 22,  42,  62,  82, 102, 122],
       [ 30,  50,  70,  90, 110, 130]])